### PR TITLE
🏳‍🌈 added colour ⭐✡🎊

### PR DESCRIPTION
**Pull request by Wattershred**
Youre welcome !!!!!!!!!!!!!

### CODE REVIEW

**Comment by Wattershred** [comment]
Please like and subscribe if you enjoyed the video, and thanks to debrand for sponsoring todays video. the links to their products are in the description below the like button. thanks again for watching. see you in the next episode

**Review by aixizu — APPROVED** [review]
this looks like a good addition

**Comment by simoncox2003** [comment]
Sick development, this has the potential to be the next chat gpt

**Comment by Wattershred** [comment]
guys we need another update

**Pull request merged**
